def wrong(num):
	if num == 10:
		print()
		print("___________")
		print("|          |")
		print("|         ( )")
		print("|         /|\\")
		print("|          |")
		print("|         / \\")
		print("|")
		print("|_____________")
		print("")

	if num == 9:
		print()
		print("___________")
		print("|          |")
		print("|         ( )")
		print("|         /|\\")
		print("|          |")
		print("|         / ")
		print("|")
		print("|_____________")
		print("")

	if num == 8: 
		print()
		print("___________")
		print("|          |")
		print("|         ( )")
		print("|         /|\\")
		print("|          |")
		print("|")
		print("|")
		print("|_____________")
		print("")

	if num == 7:
		print()
		print("___________")
		print("|          |")
		print("|         ( )")
		print("|         / \\")
		print("|")
		print("|")
		print("|")
		print("|_____________")
		print("")

	if num == 6:
		print()
		print("___________")
		print("|          |")
		print("|         ( )")
		print("|         / ")
		print("|")
		print("|")
		print("|")
		print("|_____________")
		print("")

	if num == 5:
		print()
		print("___________")
		print("|          |")
		print("|         ( )")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|_____________")
		print("")

	if num == 4:
		print()
		print("___________")
		print("|          |")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|_____________")
		print("")

	if num == 3:
		print()
		print("___________")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|_____________")
		print("")

	if num == 2:
		print()
		print("")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|")
		print("|_____________")
		print("")

	if num == 1: 
		print()
		print("")
		print("")
		print("")
		print("")
		print("")
		print("")
		print("")
		print(" _____________")
		print("")

	if num == 0:
		print()
		print("")
		print("")
		print("")
		print("")
		print("")
		print("")
		print("")
		print("")
		print("")